name: Update POT File

on:
  push:
    branches:
      - main
    paths:
      - '**/*.php'

jobs:
  make-pot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Generate .pot file
        run: |
          mkdir -p languages
          wp i18n make-pot . languages/wp-bsky-autoposter.pot --slug=wp-bsky-autoposter

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update .pot file automatically"
          branch: update-pot-file
          title: "Update .pot file automatically"
          body: |
            This pull request was automatically generated by GitHub Actions.
            It includes an updated `.pot` file based on the latest changes in `main`.
          base: main